version: "3.9"
services:
  # PostgreSQL without persistent storage for testing
  db:
    build:
      context: ./src/db
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  # Tests for db manager code
  test_db:
    build:
      context: ./src/data_collection
      dockerfile: Dockerfile.tests
    command: bash -c "bash wait-for-db.sh && sleep 10 && pytest tests/db"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    depends_on:
      - db

  # Tests for web3 code
  test_web3:
    build:
      context: ./src/data_collection
      dockerfile: Dockerfile.tests
    command: ["pytest", "tests/web3"]
