version: "3.9"
services:
  # Kafka
  zookeeper:
    image: zookeeper:3.8.0
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ./src/kafka/data/zookeeper-data/data:/data
      - ./src/kafka/data/zookeeper-data/datalog:/datalog
  kafka:
    build:
      context: ./src/kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CREATE_TOPICS=eth:1:1,etc:1:1,bsc:1:1
      - KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS=6000
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LOG_DIRS=/kafka/kafka-logs
    volumes:
      - ./src/kafka/data/kafka-data:/kafka

  # Data producers
  data_producer_eth:
    build:
      context: ./src/data_collection
    profiles: ["eth", "all"]
    depends_on:
      - kafka
  data_producer_etc:
    build:
      context: ./src/data_collection
    profiles: ["etc", "all"]
    depends_on:
      - kafka
  data_producer_bsc:
    build:
      context: ./src/data_collection
    profiles: ["bsc", "all"]
    depends_on:
      - kafka

  # Data consumers
  data_consumer_eth:
    build:
      context: ./src/data_collection
    profiles: ["eth", "all"]
    depends_on:
      - kafka
  data_consumer_etc:
    build:
      context: ./src/data_collection
    profiles: ["etc", "all"]
    depends_on:
      - kafka
  data_consumer_bsc:
    build:
      context: ./src/data_collection
    profiles: ["bsc", "all"]
    depends_on:
      - kafka

# Kafka related config
# see: https://github.com/bitnami/bitnami-docker-kafka/blob/a576f9847c9ed455645d6540a7f32e7935e6b4d7/docker-compose.yml#L24
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local