version: "3.9"
services:
  # Different configuration files for data producers
  data_producer_eth:
    command: bash -c "bash wait-for-kafka.sh && python3 -m app.main --cfg etc/cfg/dev/eth.json --mode producer"
    depends_on:
      - db

  data_producer_etc:
    command: bash -c "bash wait-for-kafka.sh && python3 -m app.main --cfg etc/cfg/dev/etc.json --mode producer"
    depends_on:
      - db

  data_producer_bsc:
    command: bash -c "bash wait-for-kafka.sh && python3 -m app.main --cfg etc/cfg/dev/bsc.json --mode producer"
    depends_on:
      - db

  data_consumer_eth:
    command: bash -c "bash wait-for-kafka.sh && python3 -m app.main --cfg etc/cfg/dev/eth.json --mode consumer"
    deploy:
      replicas: 2
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
    depends_on:
      - db

  data_consumer_etc:
    command: bash -c "bash wait-for-kafka.sh && python3 -m app.main --cfg etc/cfg/dev/etc.json --mode consumer"
    depends_on:
      - db

  data_consumer_bsc:
    command: bash -c "bash wait-for-kafka.sh && python3 -m app.main --cfg etc/cfg/dev/bsc.json --mode consumer"
    depends_on:
      - db
