version: "3.9"
services:
  # NGINX reverse proxy for connecting to erigon
  # Workaround for the default docker compose network not being able to access the host network
  # due to firewall configuration. The current firewall rules only allow 172.17.0.1 (docker0 / bridge gateway)
  # to communicate with host. Thus this proxy is running by default on the bridge network and gets connected
  # to the default docker compose network after starting the containers.
  erigon_proxy:
    build:
      context: ./src/erigon_proxy
    container_name: ${PROJECT_NAME}-erigon_proxy
    hostname: erigon_proxy
    network_mode: "bridge"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PROXY_PORT=18547
      - ERIGON_PORT=${ERIGON_PORT}
      # host.docker.internal gets translated to localhost of abacus
      - ERIGON_HOST=${ERIGON_HOST}

  # Different configuration files for data producers
  data_producer_eth:
    command: bash -c "bash wait-for-kafka.sh && python3 -m app.main --cfg etc/cfg/prod/eth.json --mode producer"
    depends_on:
      - erigon_proxy

  data_producer_etc:
    command: bash -c "bash wait-for-kafka.sh && python3 -m app.main --cfg etc/cfg/prod/etc.json --mode producer"
    depends_on:
      - erigon_proxy

  data_producer_bsc:
    command: bash -c "bash wait-for-kafka.sh && python3 -m app.main --cfg etc/cfg/prod/bsc.json --mode producer"
    depends_on:
      - erigon_proxy

  data_consumer_eth:
    command: bash -c "bash wait-for-kafka.sh && python3 -m app.main --cfg etc/cfg/prod/eth.json --mode consumer"
    deploy:
      replicas: 2
    depends_on:
      - erigon_proxy

  data_consumer_etc:
    command: bash -c "bash wait-for-kafka.sh && python3 -m app.main --cfg etc/cfg/prod/etc.json --mode consumer"
    deploy:
      replicas: 2
    depends_on:
      - erigon_proxy

  data_consumer_bsc:
    command: bash -c "bash wait-for-kafka.sh && python3 -m app.main --cfg etc/cfg/prod/bsc.json --mode consumer"
    deploy:
      replicas: 2
    depends_on:
      - erigon_proxy
