name: "Mypy"
on:
  pull_request: {}
  push:
      branches-ignore:
        - 'main'

jobs:
  run_mypy:
    runs-on: ubuntu-latest
    name: Mypy
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Mypy
        uses: jashparekh/mypy-action@v2
        with:
          path: '.'
          mypy_version: '0.910'
          #mypy_flags: '--verbose'
          #mypy_config_file: 'mypy.ini'
          requirement_files: 'src/data_collection/requirements.txt src/data_collection/requirements-tests.txt'
