name: lint

on:
  push:
    paths:
      - '*.py'

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
	  python-version: 3.7.4
	  architecture: x64
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install mypy
        run: pip install mypy
	run: mypy --ignore-missing-imports .
