
name: Web3 unit tests

on:
  push:
    branches-ignore:
      - 'main'
    paths:
      - .github/workflows/test-web3.yaml
      # Python
      - 'src/data_collection/app/web3/**'
      - 'src/data_collection/tests/web3/**'
      - 'src/data_collection/Dockerfile.tests'
      - 'src/data_collection/pytest.ini'
      - 'src/data_collection/requirements-tests.in'
      - 'src/data_collection/requirements-tests.txt'

env:
  IMAGE_NAME: ${{ github.repository }}
  GHCR: ghcr.io

jobs:
  test:
    name: web3 unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Run docker-compose.tests.yml
        run: bash scripts/tests/run-tests-web3.sh
        shell: bash
